services:
  api_myccet_infyfix_com_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: api.myccet.infyfix.com.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
